import {
  StateSchema,
  type GraphNode,
  StateGraph,
  START,
  END,
} from "@langchain/langgraph";
import { z } from "zod";
import { cohereModel, geminiModel, mistralModel } from "./models.service.js";
import { createAgent, HumanMessage, providerStrategy } from "langchain";

const state = new StateSchema({
  problem: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judgeResponse: z.object({
    solution_1_score: z.number().default(0),
    solution_2_score: z.number().default(0),
    solution_1_reasoning: z.string().default(""),
    solution_2_reasoning: z.string().default(""),
    winner: z.string().default(""),
  }),
});

const solution_node: GraphNode<typeof state> = async (state) => {
  const [solution_1, solution_2] = await Promise.all([
    cohereModel.invoke(state.problem),
    mistralModel.invoke(state.problem),
  ]);

  return {
    solution_1: solution_1?.content,
    solution_2: solution_2?.content,
  };
};

const judge_Node: GraphNode<typeof state> = async (state) => {
  const { problem, solution_1, solution_2 } = state;

  // we have to create agent for proper response !

  const judgeAgent = createAgent({
    model: geminiModel,
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().default(0),
        solution_2_score: z.number().default(0),
        solution_1_reasoning: z.string().default(""),
        solution_2_reasoning: z.string().default(""),
        winner: z.string().default(""),
      }),
    ),
    systemPrompt: `You are a judge tasked with evaluating two solutions generated by different AI models. Please provide a score out of 10 for each solution, along with your reasoning for the scores and also add the winner with some 20 to 30 word reason.`,
  });

  const judgeResponse = await judgeAgent.invoke({
    messages: [
      new HumanMessage(`
                Problem: ${problem}
                Solution 1: ${solution_1}
                Solution 2: ${solution_2}
                Please evaluate the solutions and provide scores and reasoning.
                `),
    ],
  });

  const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning,
    winner,
  } = judgeResponse.structuredResponse;

  return {
    judgeResponse: {
      solution_1_score,
      solution_2_score,
      solution_1_reasoning,
      solution_2_reasoning,
      winner,
    },
  };
};

const graph = new StateGraph(state)
  .addNode("solution_node", solution_node)
  .addNode("judge_node", judge_Node)
  .addEdge(START, "solution_node")
  .addEdge("solution_node", "judge_node")
  .addEdge("judge_node", END)
  .compile();

export default async function (userInput: string) {
  const result = await graph.invoke({
    problem: userInput,
  });

  return result;
}
